#%RAML 1.0
title: product-api
baseUri: http://localhost:8081/products
/products:
  get:
    description: to get products
    responses:
      200:
        body:
          application/json:
            example:
              {
                "productID": "7675545",
                "productName": "mule course",
                "productProvider": "Udemy",
                "productDescription": "mule dev course"
              }